apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deployment
spec:
  template:
    name: db-noticias
    labels:
      app: db-noticias
  spec:
    container:
      - name: db-noticias-container
        image: aluracursos/mysql-db:1
        ports:
          - containerPort: 3306
        envFrom:
          - configMapRef:
              name: db-configmap
  selector:
    matchLabels:
      app: db-noticias